# Generated by Django 3.0.2 on 2020-01-17 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200117_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='desctxt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='title',
        ),
    ]
