# Generated by Django 3.0.2 on 2020-01-20 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200117_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imagew',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
