# Generated by Django 3.0.2 on 2020-01-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_imagew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='imagew',
        ),
    ]
